apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: avishkarlakade/config-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "native"
            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS
              value: "classpath:/config/"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: food-delivery
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888