apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: avishkarlakade/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
            - containerPort: 8444
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: food-delivery
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8443
      targetPort: 8443
      name: https
    - port: 8444
      targetPort: 8444
      name: management