apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurantdb-pvc
  namespace: food-delivery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantdb
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantdb
  template:
    metadata:
      labels:
        app: restaurantdb
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: restaurantdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: restaurantdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantdb
  namespace: food-delivery
spec:
  type: ClusterIP
  selector:
    app: restaurantdb
  ports:
    - port: 5432
      targetPort: 5432
